In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [5]:
arr


array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [13]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [17]:
np.zeros((4,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [24]:
np.linspace(1,0.1,1000)

array([ 1.        ,  0.9990991 ,  0.9981982 ,  0.9972973 ,  0.9963964 ,
        0.9954955 ,  0.99459459,  0.99369369,  0.99279279,  0.99189189,
        0.99099099,  0.99009009,  0.98918919,  0.98828829,  0.98738739,
        0.98648649,  0.98558559,  0.98468468,  0.98378378,  0.98288288,
        0.98198198,  0.98108108,  0.98018018,  0.97927928,  0.97837838,
        0.97747748,  0.97657658,  0.97567568,  0.97477477,  0.97387387,
        0.97297297,  0.97207207,  0.97117117,  0.97027027,  0.96936937,
        0.96846847,  0.96756757,  0.96666667,  0.96576577,  0.96486486,
        0.96396396,  0.96306306,  0.96216216,  0.96126126,  0.96036036,
        0.95945946,  0.95855856,  0.95765766,  0.95675676,  0.95585586,
        0.95495495,  0.95405405,  0.95315315,  0.95225225,  0.95135135,
        0.95045045,  0.94954955,  0.94864865,  0.94774775,  0.94684685,
        0.94594595,  0.94504505,  0.94414414,  0.94324324,  0.94234234,
        0.94144144,  0.94054054,  0.93963964,  0.93873874,  0.93

In [25]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [26]:
np.random.rand(5)

array([ 0.68620306,  0.39473148,  0.66209863,  0.62538064,  0.36045168])

In [27]:
np.random.rand(5,5)

array([[ 0.43965933,  0.18773129,  0.30853782,  0.3677315 ,  0.18584074],
       [ 0.12532512,  0.8231178 ,  0.46235079,  0.05544135,  0.00591554],
       [ 0.90624695,  0.42816385,  0.09703634,  0.6842214 ,  0.64791873],
       [ 0.78189199,  0.27892999,  0.8695218 ,  0.2799757 ,  0.48126912],
       [ 0.31484528,  0.8918639 ,  0.27373953,  0.69989304,  0.72182331]])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arran = np.random.randint(0,50,10)

In [31]:
arran

array([28, 33, 29, 25,  1, 11, 16, 10, 24, 26])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arran.max()

33

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arran[5:]

array([11, 16, 10, 24, 26])

In [38]:
arran[:3]

array([28, 33, 29])

In [39]:
arran[2:4]

array([29, 25])

In [40]:
arran

array([28, 33, 29, 25,  1, 11, 16, 10, 24, 26])

In [41]:
arran[0:5]

array([28, 33, 29, 25,  1])

In [42]:
arran[0:6]

array([28, 33, 29, 25,  1, 11])

In [43]:
arran[:6]

array([28, 33, 29, 25,  1, 11])

In [44]:
arran[8:]

array([24, 26])

In [45]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [46]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
arr_2d[1:,:1]

array([[20],
       [35]])

In [48]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [49]:
arr_2d[:1]

array([[ 5, 10, 15]])

In [50]:
arr_2d[:3]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [51]:
arr_2s[,:2]

SyntaxError: invalid syntax (<ipython-input-51-37c697bec460>, line 1)

In [52]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [53]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
ans = arr > 5

In [56]:
ans

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [57]:
arr[ans]

array([ 6,  7,  8,  9, 10])

In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
arr_2d[1:3]

array([[20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d[1:2]

array([[20, 25, 30]])